// <auto-generated />
using System;
using BlazorLanguageLearningApp.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorLanguageLearningApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251028135357_AddAnswerRecords")]
    partial class AddAnswerRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.AnswerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardId")
                        .HasColumnType("int");

                    b.Property<bool>("Correct")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.ToTable("AnswersRecords");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DefinitionLanguage")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("SetId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TermLanguage")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Username");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefinitionsLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FolderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TermsLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<int>("Gems")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.AnswerRecord", b =>
                {
                    b.HasOne("BlazorLanguageLearningApp.Shared.Card", null)
                        .WithMany("PastAnswers")
                        .HasForeignKey("CardId");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Card", b =>
                {
                    b.HasOne("BlazorLanguageLearningApp.Shared.Set", null)
                        .WithMany("Cards")
                        .HasForeignKey("SetId");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Folder", b =>
                {
                    b.HasOne("BlazorLanguageLearningApp.Shared.User", null)
                        .WithMany("Folders")
                        .HasForeignKey("Username");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Set", b =>
                {
                    b.HasOne("BlazorLanguageLearningApp.Shared.Folder", null)
                        .WithMany("Sets")
                        .HasForeignKey("FolderId");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Card", b =>
                {
                    b.Navigation("PastAnswers");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Folder", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.Set", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("BlazorLanguageLearningApp.Shared.User", b =>
                {
                    b.Navigation("Folders");
                });
#pragma warning restore 612, 618
        }
    }
}
